server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nursery_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create


custom:
  property: "ma prop custom"
  other: "thing"
  number: 3
  list:
    - 1
    - 2
    - 3